config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path, reverse_lazy
from django.shortcuts import redirect
from django.views import defaults as default_views
from django.views.generic import TemplateView

todos_redirect = lambda request: redirect(reverse_lazy("todos:list"))

urlpatterns = [
    path("", todos_redirect, name="home"),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("django_crud_example.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    path("todos/", include("django_crud_example.todos.urls"), name="todos"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

django_crud_example/todos/urls.py
from django.urls import include, path
from .views import (
    ListTodosView,
    CreateTodoView,
    UpdateTodoView,
    DeleteTodoView,
    DetailTodoView,
)

app_name = "todos"
urlpatterns = [
    path("list/", ListTodosView.as_view(), name="list"),
    path("create/", CreateTodoView.as_view(), name="create"),
    path("update/<int:pk>", UpdateTodoView.as_view(), name="update"),
    path("delete/<int:pk>", DeleteTodoView.as_view(), name="delete"),
    path("detail/<int:pk>", DetailTodoView.as_view(), name="detail"),
]

django_crud_example/users/urls.py
from django.urls import path

from django_crud_example.users.views import (
    user_detail_view,
    user_redirect_view,
    user_update_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

django_crud_example/todos/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _


class Todo(models.Model):
    title = models.CharField(_("Titulo"), max_length=20)
    description = models.TextField(_("Descripción"))
    priority = models.CharField(
        _("Prioridad"), max_length=1, choices=(("1", "1"), ("2", "2"), ("3", "3"))
    )
    created_at = models.DateTimeField(_("Fecha Creación"), auto_now_add=True)

    def __str__(self):
        return self.title

django_crud_example/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


class User(AbstractUser):
    """Default user for django_crud_example."""

    #: First and last name do not cover name patterns around the globe
    name = CharField(_("Name of User"), blank=True, max_length=255)

    def get_absolute_url(self):
        """Get url for user's detail view.

        Returns:
            str: URL for user detail.

        """
        return reverse("users:detail", kwargs={"username": self.username})

django_crud_example/users/forms.py
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class UserChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(admin_forms.UserCreationForm):

    error_message = admin_forms.UserCreationForm.error_messages.update(
        {"duplicate_username": _("This username has already been taken.")}
    )

    class Meta(admin_forms.UserCreationForm.Meta):
        model = User

    def clean_username(self):
        username = self.cleaned_data["username"]

        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username

        raise ValidationError(self.error_messages["duplicate_username"])

django_crud_example/todos/views.py
from django.views.generic import (
    ListView,
    CreateView,
    UpdateView,
    DeleteView,
    DetailView,
)
from django.urls import reverse_lazy

from .models import Todo


class ListTodosView(ListView):
    model = Todo


class DetailTodoView(DetailView):
    model = Todo


class CreateTodoView(CreateView):
    model = Todo
    fields = ["title", "description", "priority"]

    def get_success_url(self):
        return reverse_lazy("todos:list")


class UpdateTodoView(UpdateView):
    model = Todo
    fields = ["title", "description", "priority"]

    def get_success_url(self):
        return reverse_lazy("todos:list")


class DeleteTodoView(DeleteView):
    model = Todo

    def get_success_url(self):
        return reverse_lazy("todos:list")

django_crud_example/users/views.py
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, UpdateView):

    model = User
    fields = ["name"]

    def get_success_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})

    def get_object(self):
        return User.objects.get(username=self.request.user.username)

    def form_valid(self, form):
        messages.add_message(
            self.request, messages.INFO, _("Infos successfully updated")
        )
        return super().form_valid(form)


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

django_crud_example/templates/base.html
{% load static i18n %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>{% block title %}django_crud_example{% endblock title %}</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="Behold My Awesome Project!">
  <meta name="author" content="Daniel Roy Greenfeld">

  <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
  <!--[if lt IE 9]>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
    <![endif]-->

  <link rel="icon" href="{% static 'images/favicons/favicon.ico' %}">

  {% block css %}

  <!-- Latest compiled and minified Bootstrap CSS -->
  <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">


  <!-- Your stuff: Third-party CSS libraries go here -->

  <!-- This file stores project-specific CSS -->

  <link href="{% static 'css/project.css' %}" rel="stylesheet">


  {% endblock %}

</head>

<body>

  <div class="container">

    {% if messages %}
    {% for message in messages %}
    <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}<button type="button"
        class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button></div>
    {% endfor %}
    {% endif %}

    <div class="mt-2 container">
      {% block content %}
      
      {% endblock content %}
    </div>

  </div> <!-- /container -->

  {% block modal %}{% endblock modal %}

  <!-- Le javascript
    ================================================== -->
  <!-- Placed at the end of the document so the pages load faster -->
  {% block javascript %}

  <!-- Bootstrap JS and its dependencies-->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
    integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
    crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
    integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
    crossorigin="anonymous"></script>

  <!-- Your stuff: Third-party javascript libraries go here -->

  <!-- place project specific Javascript in this file -->

  <script src="{% static 'js/project.js' %}"></script>

  {% endblock javascript %}
</body>

</html>

django_crud_example/templates/pages/home.html
{% extends "base.html" %}

django_crud_example/templates/todos/todo_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}Todos{% endblock %}

{% block content %}
    <div class="jumbotron">
        <h1 class="display-4">{{ todo.title }}</h1>
        <p class="lead">{{ todo.description }}</p>
        <hr class="my-4">
        <p>Prioridad:</p>
        <p class="lead ml-3">{{ todo.priority }}</p>
        <p>Fecha Creación:</p>
        <p class="lead ml-3">{{ todo.created_at }}</p>
        <p class="lead">
            <a 
                class="btn btn-primary btn-lg"
                href="{% url 'todos:list' %}"
                role="button"
                >
                Regresar
            </a>
        </p>
    </div>
{% endblock %}

django_crud_example/templates/todos/todo_form.html
{% extends "base.html" %}
{% load static %}

{% block title %}Todos{% endblock %}

{% block content %}
    {% load crispy_forms_tags %}
    <nav 
        class="navbar navbar-light bg-info justify-content-center mb-4" style="border-radius:0.5rem;"
        >
        <a class="navbar-brand">
            <h1>
                {% if 'update' in request.path %}
                    Editar Todo
                {% else %}
                    Crear Todo
                {% endif %}
            </h1>
        </a>
    </nav>

    <div 
        style="width:100%;
        display:flex;
        flex-direction:column;
        align-items:center;
        justify-content:center;"
        >
        <form 
            id="form" 
            method="POST"
            {% if "update" in request.path %} 
                action="{{ request.path }}" 
            {% else %} 
                action="{% url 'todos:create' %}" 
            {% endif %}
            style="width:500px"
            >
            {% csrf_token %}
            {% crispy form %}
            <div>
                <button 
                    id="btnSubmit"
                    style="width:100px"
                    type="submit"
                    class="btn btn-primary"
                    >
                    Guardar
                </button>
                <a 
                    style="width:100px"
                    href="{% url 'todos:list' %}"
                    class="btn btn-danger"
                    >
                    Cancelar
                </a>
            </div>
        </form>
    </div>

{% endblock %}

{% block javascript %}
    <script>
        const btnSubmit = document.getElementById("btnSubmit");
        const form = document.getElementById("form");

        btnSubmit.onclick = () => {
            form.submit();
        }
    </script>
{% endblock %}

django_crud_example/templates/todos/todo_list.html
{% extends "base.html" %}
{% load static %}
{% load string_utils %}
{% block title %}Todos{% endblock %}

{% block content %}

<table class="table table-striped table-hover caption-top">
    <thead>
    <tr class="table-primary">
        <th scope="col">Titulo</th>
        <th scope="col">Descripción</th>
        <th scope="col">Prioridad</th>
        <th scope="col">Fecha de Creación</th>
        <th scope="col">
            <div 
            style="display:flex; flex-direction:row; justify-content:center; align-items:end;"
            >
                <a href="{% url 'todos:create' %}" class="btn btn-success">Nuevo</a>
            </div>
        </th>
    </tr>
    </thead>
    <tbody> 
        {% for todo in object_list %}
        <tr>
            <td>
                <a href="{% url 'todos:detail' todo.pk %}">{{ todo.title }}</a>
            </td>
            <td>
                <a href="{% url 'todos:detail' todo.pk %}">
                    {{ todo.description|cut_text }}
                </a>
            </td>
            <td>
                <a href="{% url 'todos:detail' todo.pk %}">{{ todo.priority }}</a>
            </td>
            <td>
                <a href="{% url 'todos:detail' todo.pk %}">{{ todo.created_at }}</a>
            </td>
            <td>
            <div style="display:flex; flex-direction: row; justify-content:center;">
                <a href="{% url 'todos:update' todo.pk %}" class="btn btn-info mr-2">Editar</a>
                <form action="{% url 'todos:delete' todo.pk %}" method="POST">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger">Hecho</button>
                </form>
            </div>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %}

django_crud_example/templates/users/user_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}User: {{ object.username }}{% endblock %}

{% block content %}
<div class="container">

  <div class="row">
    <div class="col-sm-12">

      <h2>{{ object.username }}</h2>
      {% if object.name %}
        <p>{{ object.name }}</p>
      {% endif %}
    </div>
  </div>

{% if object == request.user %}
<!-- Action buttons -->
<div class="row">

  <div class="col-sm-12">
    <a class="btn btn-primary" href="{% url 'users:update' %}" role="button">My Info</a>
    <a class="btn btn-primary" href="{% url 'account_email' %}" role="button">E-Mail</a>
    <!-- Your Stuff: Custom user template urls -->
  </div>

</div>
<!-- End Action buttons -->
{% endif %}


</div>
{% endblock content %}

django_crud_example/templates/users/user_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}{{ user.username }}{% endblock %}

{% block content %}
  <h1>{{ user.username }}</h1>
  <form class="form-horizontal" method="post" action="{% url 'users:update' %}">
    {% csrf_token %}
    {{ form|crispy }}
    <div class="control-group">
      <div class="controls">
        <button type="submit" class="btn btn-primary">Update</button>
      </div>
    </div>
  </form>
{% endblock %}